version: '3.8'

services:
  metadata-remote:
    image: ghcr.io/wow-signal-dev/metadata-remote:latest
    container_name: metadata-remote
    restart: unless-stopped
    ports:
      - "8338:8338"
    volumes:
      - /your/music/path:/music  # CHANGE THIS: Point to your music directory
    environment:
      - UID=1000
      - GID=1000
    user: "1000:1000"
