version: '3.8'

services:
  metadata-remote:
    image: ghcr.io/wow-signal-dev/metadata-remote:latest
    container_name: metadata-remote
    ports:
      - "8338:8338"
    volumes:
      - /path/to/your/music:/music  # Users must change this
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    
