version: '3.8'
services:
  metadata-remote:
    image: ghcr.io/wow-signal-dev/metadata-remote:latest
    container_name: metadata-remote
    ports:
      - "8338:8338"
    volumes:
      - /PATH/TO/YOUR/MUSIC:/music  # Users must change this
      # To add multiple music folders, mount them as subdirectories:
      # - /path/to/music1:/music/Library1
      # - /path/to/music2:/music/Library2
      # ... etc.
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8338/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
